# This file was generated by GoReleaser. DO NOT EDIT.
cask "ptah" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "1d28cc857bb768ead74c1680f4e628d86e979cdc9c345097932ea902d5a5a99b"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cea5ba80810110ce72b70a2941bf47861a5f36268fb1443a8d6720fa7a725f77"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c59dfae2d1d954b9a4145a78d39268f2f78a955f46f969b7d9840d853cf3e97a"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c124093f3dc825077bfc4cc0b50207ae4b82499c44cc08a7e356fd7e787b65d6"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ptah"
  desc "Ptah manages database change across schemas and persistent inference state"
  homepage "https://ptah.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ptah"
  binary "ptah-compat"
  binary "ptah-ls"

  # No zap stanza required

  caveats <<~EOS
    ptah-edge installs the same three binaries from master. Install only one of
    the two: brew uninstall ptah-edge before installing this one.
  EOS
end
