# This file was generated by GoReleaser. DO NOT EDIT.
cask "ptah" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "8516e2f4eb3c5f24668113ed74b9e08183c2889f9fec5b877e2a74b6886322ff"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "26574aa600c46014ba8a4514fab9b11ff33a14713aacddddbee5c2a4847aadf9"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "09c959718ae3eb10bd0a6c38f2b7a4c1b1d584e26b5e95921a1697102782c8a3"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "986ce43ca151a6c6ce1d3fa7d592de9a743d8d2c9c07a29456bc7a09afcd157e"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ptah"
  desc "Ptah manages database change across schemas and persistent inference state"
  homepage "https://ptah.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ptah"
  binary "ptah-compat"
  binary "ptah-ls"

  # No zap stanza required

  caveats <<~EOS
    ptah-edge installs the same three binaries from master. Install only one of
    the two: brew uninstall ptah-edge before installing this one.
  EOS
end
