# This file was generated by GoReleaser. DO NOT EDIT.
cask "ptah" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "de0ef241bff693e0feb47b6c7d1657c8788b1a04e3794dc3fad8f67313a579cd"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "28c3ea68d75373eb68c3bb6e1353de8c8592f93d32e35e94ff6b62191d2fe0b6"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "70797ab2d064db119afe80157b6eceb712a313575043b4290d878430f57b12d8"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ae6970de0c9bbee4c2f93e64a77a2e1af47f080b431d63e5c0960216b65054b8"
      url "https://github.com/stokaro/ptah/releases/download/v#{version}/ptah_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ptah"
  desc "Ptah manages database change across schemas and persistent inference state"
  homepage "https://ptah.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ptah"
  binary "ptah-compat"
  binary "ptah-ls"

  # No zap stanza required

  caveats <<~EOS
    ptah-edge installs the same three binaries from master. Install only one of
    the two: brew uninstall ptah-edge before installing this one.
  EOS
end
