# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ptah < Formula
  desc "Ptah manages database change across schemas and persistent inference state"
  homepage "https://ptah.run"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stokaro/ptah/releases/download/v0.4.0/ptah_0.4.0_darwin_amd64.tar.gz"
      sha256 "97233b0197335b8eab5a70fb35a46eada8fbc554e260ee071f1cc9b37d1710d4"

      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stokaro/ptah/releases/download/v0.4.0/ptah_0.4.0_darwin_arm64.tar.gz"
      sha256 "9d3770db260d3f14857c886184ddf628f43b882f2533b60b166b4b9a362f7d92"

      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stokaro/ptah/releases/download/v0.4.0/ptah_0.4.0_linux_amd64.tar.gz"
      sha256 "044f7f87220052848f839d0a062d2b7207dbd1759e863ea4a4c112010ab2759e"
      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stokaro/ptah/releases/download/v0.4.0/ptah_0.4.0_linux_arm64.tar.gz"
      sha256 "8fddd584d57338a47f8bee90f861c7f672abd346ec46488446521bbd3a6e15f2"
      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
  end

  def caveats
    <<~EOS
      ptah-edge installs the same three binaries from master. Install only one of
      the two: brew uninstall ptah-edge before installing this one.
    EOS
  end
end
