# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ptah < Formula
  desc "Ptah manages database change across schemas and persistent inference state"
  homepage "https://ptah.run"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stokaro/ptah/releases/download/v0.5.0/ptah_0.5.0_darwin_amd64.tar.gz"
      sha256 "76be5e7acfea02af379d35f163a441ed439a09fdc972b61a0f98aa22428a8ea7"

      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stokaro/ptah/releases/download/v0.5.0/ptah_0.5.0_darwin_arm64.tar.gz"
      sha256 "252495d0d1098df30921e3281009390e170cfcd4c9ef24033dafb02bc922db64"

      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stokaro/ptah/releases/download/v0.5.0/ptah_0.5.0_linux_amd64.tar.gz"
      sha256 "e80a6490c60a27bb5204a90486ab59bac6b3f4f9f4efefd3a78453d1e1e57c37"
      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stokaro/ptah/releases/download/v0.5.0/ptah_0.5.0_linux_arm64.tar.gz"
      sha256 "3239ddd5efb1305d358261f93451ac693c4d23a8d81ecddc1a5e23374c673103"
      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
  end

  def caveats
    <<~EOS
      ptah-edge installs the same three binaries from master. Install only one of
      the two: brew uninstall ptah-edge before installing this one.
    EOS
  end
end
