# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ptah < Formula
  desc "Ptah manages database change across schemas and persistent inference state"
  homepage "https://github.com/stokaro/ptah"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stokaro/ptah/releases/download/v0.3.0/ptah_0.3.0_darwin_amd64.tar.gz"
      sha256 "2df1a8c3ceff5341404dff89ccda5aca1fd002301508eb256cf971927c1b5ec7"

      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stokaro/ptah/releases/download/v0.3.0/ptah_0.3.0_darwin_arm64.tar.gz"
      sha256 "f88d5ba4daaaae6caf578564cbc5a9bb77349296197d44fdbd208e8ed68f373b"

      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stokaro/ptah/releases/download/v0.3.0/ptah_0.3.0_linux_amd64.tar.gz"
      sha256 "f46c0ae281c4ca77395f41a82c25f77d1541e0307227d820d8c4d3a414764d67"
      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stokaro/ptah/releases/download/v0.3.0/ptah_0.3.0_linux_arm64.tar.gz"
      sha256 "93a186a5a9775c1954d23aa9b7a2b131970ad9253104882de23c6027f94231b2"
      define_method(:install) do
        bin.install "ptah"
        bin.install "ptah-compat"
        bin.install "ptah-ls"
      end
    end
  end

  conflicts_with "stokaro/ptah/ptah-edge"
end
